title: 'Vue Components'
modelClass: DEfr\VueManager\Models\Component
list: $/defr/vuemanager/models/component/columns.yaml
recordUrl: 'defr/vuemanager/components/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
showSorting: 1
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
